PROMPT Dropping tablespace MMF_9_12_DATA.
DROP TABLESPACE "MMF_9_12_DATA" INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
PROMPT Dropping tablespace MMF_9_12_IDX.
DROP TABLESPACE "MMF_9_12_IDX" INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
