ALTER TABLE STAGE ADD CONSTRAINT STAGE_PROJECT_FK FOREIGN KEY(PROJECT_ID) REFERENCES PROJECT(ID) ON DELETE CASCADE;
CREATE INDEX STAGE_PROJECT_FK_IDX ON STAGE(PROJECT_ID);

ALTER TABLE PROJECT_DEVELOPER_ROLE ADD CONSTRAINT PROJECT_DEVELOPER_ROLE_PROJECT_FK FOREIGN KEY(PROJECT_ID) REFERENCES PROJECT(ID) ON DELETE CASCADE;
CREATE INDEX PROJECT_DEVELOPER_ROLE_PROJECT_FK_IDX ON PROJECT_DEVELOPER_ROLE(PROJECT_ID);

ALTER TABLE PROJECT_DEVELOPER_ROLE ADD CONSTRAINT PROJECT_DEVELOPER_ROLE_DEVELOPER_FK FOREIGN KEY(DEVELOPER_ID) REFERENCES DEVELOPER(ID) ON DELETE CASCADE;
CREATE INDEX PROJECT_DEVELOPER_ROLE_DEVELOPER_FK_IDX ON PROJECT_DEVELOPER_ROLE(DEVELOPER_ID);

ALTER TABLE PROJECT_DEVELOPER_ROLE ADD CONSTRAINT PROJECT_DEVELOPER_ROLE_ROLE_FK FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID) ON DELETE CASCADE;
CREATE INDEX PROJECT_DEVELOPER_ROLE_ROLE_FK_IDX ON PROJECT_DEVELOPER_ROLE(ROLE_ID);

ALTER TABLE TEAM_DEVELOPER ADD CONSTRAINT TEAM_DEVELOPER_DEVELOPER_FK FOREIGN KEY(DEVELOPER_ID) REFERENCES DEVELOPER(ID) ON DELETE CASCADE;
CREATE INDEX TEAM_DEVELOPER_DEVELOPER_FK_IDX ON TEAM_DEVELOPER(DEVELOPER_ID);

ALTER TABLE TEAM_DEVELOPER ADD CONSTRAINT TEAM_DEVELOPER_TEAM_FK FOREIGN KEY(TEAM_ID) REFERENCES TEAM(ID) ON DELETE CASCADE;
CREATE INDEX TEAM_DEVELOPER_TEAM_FK_IDX ON TEAM_DEVELOPER(TEAM_ID);

ALTER TABLE TEAM_PROJECT ADD CONSTRAINT TEAM_PROJECT_PROJECT_FK FOREIGN KEY(PROJECT_ID) REFERENCES PROJECT(ID) ON DELETE CASCADE;
CREATE INDEX TEAM_PROJECT_PROJECT_FK_IDX ON TEAM_PROJECT(PROJECT_ID);

ALTER TABLE TEAM_PROJECT ADD CONSTRAINT TEAM_PROJECT_TEAM_FK FOREIGN KEY(TEAM_ID) REFERENCES TEAM(ID) ON DELETE CASCADE;
CREATE INDEX TEAM_PROJECT_TEAM_FK_IDX ON TEAM_PROJECT(TEAM_ID);

ALTER TABLE DEVELOPER_SKILL ADD CONSTRAINT DEVELOPER_SKILL_DEVELOPER_FK FOREIGN KEY(DEVELOPER_ID) REFERENCES DEVELOPER(ID) ON DELETE CASCADE;
CREATE INDEX DEVELOPER_SKILL_DEVELOPER_FK_IDX ON DEVELOPER_SKILL(DEVELOPER_ID);

ALTER TABLE DEVELOPER_SKILL ADD CONSTRAINT DEVELOPER_SKILL_SKILL_FK FOREIGN KEY(SKILL_ID) REFERENCES SKILL(ID) ON DELETE CASCADE;
CREATE INDEX DEVELOPER_SKILL_SKILL_FK_IDX ON DEVELOPER_SKILL(SKILL_ID);

ALTER TABLE TASK ADD CONSTRAINT TASK_STAGE_FK FOREIGN KEY(STAGE_ID) REFERENCES STAGE(ID) ON DELETE CASCADE;
CREATE INDEX TASK_STAGE_FK_IDX ON TASK(STAGE_ID);

ALTER TABLE TASK ADD CONSTRAINT TASK_STATUS_FK FOREIGN KEY(TASK_STATUS_ID) REFERENCES TASK_STATUS(ID) ON DELETE CASCADE;
CREATE INDEX TASK_STATUS_FK_IDX ON TASK(TASK_STATUS_ID);

ALTER TABLE DEVELOPER_TASK ADD CONSTRAINT DEVELOPER_TASK_TASK_FK FOREIGN KEY(TASK_ID) REFERENCES TASK(ID) ON DELETE CASCADE;
CREATE INDEX DEVELOPER_TASK_TASK_FK_IDX ON DEVELOPER_TASK(TASK_ID);

ALTER TABLE DEVELOPER_TASK ADD CONSTRAINT DEVELOPER_TASK_DEVELOPER_FK FOREIGN KEY(DEVELOPER_ID) REFERENCES DEVELOPER(ID) ON DELETE CASCADE;
CREATE INDEX DEVELOPER_TASK_DEVELOPER_FK_IDX ON DEVELOPER_TASK(DEVELOPER_ID);
