DROP TABLE DEPARTMENT;
DROP TABLE TASK_STATUS;
DROP TABLE PROJECT;
DROP TABLE STAGE;
DROP TABLE DEVELOPER;
DROP TABLE TASK;
DROP TABLE SKILL;
DROP TABLE DEVELOPER_TASK;
DROP TABLE DEVELOPER_SKILL;
DROP TABLE TEAM;
DROP TABLE TEAM_PROJECT;
DROP TABLE TEAM_DEVELOPER;
DROP TABLE PROJECT_DEVELOPER_ROLE;
DROP TABLE ROLE;
DROP TABLE DATA_TABLE;



