DEFINE LOCATION = &&1
DEFINE DATA_TABLESPACE_NAME = 'MMF_9_12_DATA'
DEFINE DATA_FILE_NAME = '&&LOCATION&&DATA_TABLESPACE_NAME..DBF'
DEFINE INDEX_TABLESPACE_NAME = 'MMF_9_12_IDX'
DEFINE INDEX_FILE_NAME = '&&LOCATION&&INDEX_TABLESPACE_NAME..DBF'
PROMPT Creating tablespace MMF_9_12_DATA.
CREATE SMALLFILE TABLESPACE &&DATA_TABLESPACE_NAME DATAFILE '&&DATA_FILE_NAME' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 1G EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
PROMPT Creating tablespace MMF_9_12_IDX.
CREATE SMALLFILE TABLESPACE &&INDEX_TABLESPACE_NAME DATAFILE '&&INDEX_FILE_NAME' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 1G EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
