DELETE FROM DEPARTMENT;
DELETE FROM TASK_STATUS;
DELETE FROM PROJECT;
DELETE FROM STAGE;
DELETE FROM DEVELOPER;
DELETE FROM TASK;
DELETE FROM SKILL;
DELETE FROM DEVELOPER_TASK;
DELETE FROM DEVELOPER_SKILL;
DELETE FROM TEAM;
DELETE FROM TEAM_PROJECT;
DELETE FROM TEAM_DEVELOPER;
DELETE FROM PROJECT_DEVELOPER_ROLE;
DELETE FROM ROLE;
DELETE FROM DATA_TABLE;



